resource_rules:
  issues:
    rules:
      - name: Label stale issues
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: weeks
            interval: 4
          state: opened
          forbidden_labels:
            - status::backlog
            - status::blocked
            - status::in_progress
            - status::stale
        actions:
          labels:
            - status::stale
          comment: |
            (This is an automated action)
            
            This issue did not receive an update in the last 4 weeks. Please take a look again and update the issue with new details, otherwise the issue will be automatically closed in 2 weeks. Thank you!
      - name: Close stale issues
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: weeks
            interval: 2
          state: opened
          labels:
              - status::stale
        actions:
          status: close
          comment: |
            (This is an automated action)
            
            This issue is closed automatically
